spring:
  application:
    name: pre-onboarding-backend

  profiles:
    include:
      - secret # - ??? ? ? ? ????

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL 8?? ??? ?? ??
    open-in-view: false # ? ??? ??? ??? ??? EntityManager? ??? ?? / ??? ??? ??? ???? ?? false? ??
    hibernate:
      ddl-auto: update

    defer-datasource-initialization: true # ????? 2.5 ???? ?? sql ??? ??? ???

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # cj? ?????
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username:
    password: 

  sql: # ?? ??????? sql ????? ????
    init:
      mode: always


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace # console?? ? ? ???