spring:
  application:
    name: pre-onboarding-backend

  profiles:
    include:
      - secret # - ??? ? ? ? ????

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true # ????? 2.5 ???? ?? sql ??? ??? ???

  sql: # ?? ??????? sql ????? ????
    init:
      mode: always


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace # console?? ? ? ???